### ISSUE TITLE
apparently this happens when the transmission and the input come back quickly

### ISSUE THREAD

**Issue by senhor-R** [dayvsonsales/CAM4Recorder#1]
apparently this occurs when the transmission is interrupted and returns quickly, the problem is that it leaves the recording with much delay.

Failed to reload playlist: Unable to open URL: https://cs1807.cam4.com/cam4-edge-live/_definst_/amlst:modelcam-321-c679a94c-e29b-4efc-82a2-5f3d54154756_aac/chunklist_w165900569.m3u8?referer=www.cam4.com&timestamp=1589459363833 (404 Client Error: Not Found for url: https://cs1807.cam4.com/cam4-edge-live/_definst_/amlst:modelcam-321-c679a94c-e29b-4efc-82a2-5f3d54154756_aac/chunkl

**Comment by senhor-R** [comment]
this error annoys

**Comment by dayvsonsales** [comment]
You can control this editing the checkInterval variable at ``config.conf``. Change it to 10 seconds or less for example and this delay will be reduced. But I don't recommend this change because it will spam CAM4's severs.

**Comment by senhor-R** [comment]
help me remove this message
the terminal gets polluted

**Comment by dayvsonsales** [comment]
I need to inspect this. Give me the entire error message or a screenshot of your terminal. I need more information because I don't know how to reproduce this behaviour.

**Comment by senhor-R** [comment]
terminal log or system log

**Comment by senhor-R** [comment]
> Eu preciso inspecionar isso. Dê-me toda a mensagem de erro ou uma captura de tela do seu terminal. Preciso de mais informações porque não sei como reproduzir esse comportamento.

esse erro aparece quando a conexão da pessoa que está transmitindo fica instável.

**Comment by senhor-R** [comment]
is it possible to hide this error message?

**Comment by dayvsonsales** [comment]
Yes. Actually it is hidden. I don't know why you are seeing this exception. Maybe its a problem with your environment (aka OS).

**Comment by senhor-R** [comment]
is it some relationship with traceback ?

**Comment by dayvsonsales** [comment]
Yes. I think that Linux and MacOS python version differs in the way they catch exceptions because I'm in a Mac environment and I can't see this exception, even when I put a wrong URL hardcoded in the script. So, I need to take a look deeper.

**Comment by senhor-R** [comment]
python3 CAM4Recorder.py &, it does not solve, what code to hide traceback? I want to test.

**Comment by dayvsonsales** [comment]
Try putting the follwing code bellow Streamlink initialization (``session = Streamlink()``: 

``
session.set_loglevel('none')
``

**Comment by senhor-R** [comment]
the error message keeps showing

**Comment by dayvsonsales** [comment]
Try this instead: 

`` 
session = Streamlink()
session.set_loglevel('none')
session.set_logoutput(open('log.txt', 'w'))
``

**Comment by senhor-R** [comment]
the error message keeps showing, you better not waste time on it.

**Comment by dayvsonsales** [comment]
Yes. But just to know, what is your operating system and your python version?

**Comment by senhor-R** [comment]
Linux Parrot OS Home, Python 3.8

**Comment by senhor-R** [comment]
![Screenshot at 2020-05-16 15-12-11](https://user-images.githubusercontent.com/34902724/82127121-a43c0f00-9787-11ea-9cab-59229d4b5fde.png)

**Comment by senhor-R** [comment]
> Yes. But just to know, what is your operating system and your python version?

https://parrotsec.org/download/

**Comment by senhor-R** [comment]
please test the script on this distro.
