### ISSUE TITLE
How to print on same line, clearing previous text?

### ISSUE THREAD

**Issue by senhor-R** [dayvsonsales/CAM4Recorder#3]
![vokoscreen-2020-05-15_13-51-19](https://user-images.githubusercontent.com/34902724/82076301-088d9e80-96b4-11ea-887a-437cb84514ea.gif)

**Comment by dayvsonsales** [comment]
Try the following code: 
``` 
os.system('cls||clear')  
print("{} not online Next check in {} seconds".format(notonline, i), end="\n")  
print("the following models are being recorded: {}".format(recording), end="\r")  
time.sleep(1)
```

Edit CAM4Recorder.py and in the last put this code.
