### ISSUE TITLE
I'm having duplicate files

### ISSUE THREAD

**Issue by senhor-R** [dayvsonsales/CAM4Recorder#4]
I'm having duplicate files, I don't know what's going on.

![vokoscreen-2020-05-16_11-25-54](https://user-images.githubusercontent.com/34902724/82122158-40561e00-9768-11ea-9b98-eaf8fac064cc.gif)

**Comment by dayvsonsales** [comment]
Your terminal doesn't show duplicated files. Be more specific, please.
