### ISSUE TITLE
help

### ISSUE THREAD

**Issue by senhor-R** [dayvsonsales/CAM4Recorder#5]
it would be possible to make the script wait a few seconds before finalizing the download, the Camgirls internet is dropping all the time.

**Comment by dayvsonsales** [comment]
I'll take a look soon.

**Comment by senhor-R** [comment]
> I'll take a look soon.

thank you

**Comment by senhor-R** [comment]
`import re

from streamlink.plugin import Plugin
from streamlink.plugin.api import http, useragents, validate
from streamlink.stream import HLSStream, RTMPStream
from streamlink.utils import parse_json


class Cam4(Plugin):
    _url_re = re.compile(r'https?://([a-z]+\.)?cam4.com/.+')
    _video_data_re = re.compile(r"flashData: (?P<flash_data>{.*}), hlsUrl: '(?P<hls_url>.+?)'")

    _flash_data_schema = validate.Schema(
        validate.all(
            validate.transform(parse_json),
            validate.Schema({
                'playerUrl': validate.url(),
                'flashVars': validate.Schema({
                    'videoPlayUrl': validate.text,
                    'videoAppUrl': validate.url(scheme='rtmp')
                })
            })
        )
    )

    @classmethod
    def can_handle_url(cls, url):
        return Cam4._url_re.match(url)

    def _get_streams(self):
        res = http.get(self.url, headers={'User-Agent': useragents.ANDROID})
        match = self._video_data_re.search(res.text)
        if match is None:
            return

        hls_streams = HLSStream.parse_variant_playlist(
            self.session,
            match.group('hls_url'),
            headers={'Referer': self.url}
        )
        for s in hls_streams.items():
            yield s

        rtmp_video = self._flash_data_schema.validate(match.group('flash_data'))
        rtmp_stream = RTMPStream(self.session, {
            'rtmp': rtmp_video['flashVars']['videoAppUrl'],
            'playpath': rtmp_video['flashVars']['videoPlayUrl'],
            'swfUrl': rtmp_video['playerUrl']
        })
        yield 'live', rtmp_stream


__plugin__ = Cam4`


is your CAM4.py plugin like this?

**Comment by dayvsonsales** [comment]
> `import re
> 
> from streamlink.plugin import Plugin
> from streamlink.plugin.api import http, useragents, validate
> from streamlink.stream import HLSStream, RTMPStream
> from streamlink.utils import parse_json
> 
> class Cam4(Plugin):
> _url_re = re.compile(r'https?://([a-z]+.)?cam4.com/.+')
> _video_data_re = re.compile(r"flashData: (?P<flash_data>{.*}), hlsUrl: '(?P<hls_url>.+?)'")
> 
> ```
> _flash_data_schema = validate.Schema(
>     validate.all(
>         validate.transform(parse_json),
>         validate.Schema({
>             'playerUrl': validate.url(),
>             'flashVars': validate.Schema({
>                 'videoPlayUrl': validate.text,
>                 'videoAppUrl': validate.url(scheme='rtmp')
>             })
>         })
>     )
> )
> 
> @classmethod
> def can_handle_url(cls, url):
>     return Cam4._url_re.match(url)
> 
> def _get_streams(self):
>     res = http.get(self.url, headers={'User-Agent': useragents.ANDROID})
>     match = self._video_data_re.search(res.text)
>     if match is None:
>         return
> 
>     hls_streams = HLSStream.parse_variant_playlist(
>         self.session,
>         match.group('hls_url'),
>         headers={'Referer': self.url}
>     )
>     for s in hls_streams.items():
>         yield s
> 
>     rtmp_video = self._flash_data_schema.validate(match.group('flash_data'))
>     rtmp_stream = RTMPStream(self.session, {
>         'rtmp': rtmp_video['flashVars']['videoAppUrl'],
>         'playpath': rtmp_video['flashVars']['videoPlayUrl'],
>         'swfUrl': rtmp_video['playerUrl']
>     })
>     yield 'live', rtmp_stream
> ```
> 
> **plugin** = Cam4`
> 
> is your CAM4.py plugin like this?

I think this is from another repository, not mine. And this is more sophisticated than mine, you should give a try if it solves your problem.

**Comment by senhor-R** [comment]
help me port to youtube-dl

**Comment by dayvsonsales** [comment]
Hello, I'm sorry but I never did have touch this library, so I'm unable to help you. But I'm sure that you'll do a great job!

**Comment by senhor-R** [comment]
vou fazer uns testes
